export * from './Header';
export * from './Sharedtext';
export { default as MetaTags } from './MetaTags';
export { default as DifferentBg } from './DifferentBg';
export { default as ContactForm } from './ContactForm';
export { default as TagCard } from './TagCard';
export { default as DescCard } from './DescCard';
export { default as GreenCirle } from './GreenCirle';
export { default as HeroTags } from './HeroTags';
export { default as HeroTexts } from './HeroTexts';
export { default as FeedBack } from './FeedBack';
export { default as TeamCard } from './TeamCard';
export { default as WorksShowCaseCard } from './WorksShowCaseCard';
