export const globalStyles = {
  primaryColor: '#1312C9',
  textColor: '#323B4B',
  secondaryColor: '#061173',
  goldenColor: '#FFC700',
  whiteColor: '#FFF',
  smallTextFontSize: '14px',
  headerFontSize: '36px',
  headerFontWeight: 600,
  width: '100%',
  px: { base: 3, xl: 10, '2xl': 0 },
  blackColor: '#110F0F',
  fontFamily: " 'Poppins', sans-serif",
  containerWidth: {
    base: '100%',
    xl: '1200px',
    '2xl': '1450px',
  },
  sectionStyle: {
    width: '100%',
    px: { base: 3, xl: 10, '2xl': 0 },
    align: 'center',
    justifyContent: 'center',
  },
};
