name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: node 16
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn lint
 
